In [21]:
import torch
from torch.autograd import Variable

# unsqueeze函数
`torch.unsqueeze(input, dim) → Tensor`

返回在指定位置插入的尺寸为1的新张量。

返回的张量与此张量共享相同的基础数据。

参数`dim`的范围在$[-input.dim() - 1, input.dim() + 1)$，负数`dim`转换为`dim = dim + input.dim() + 1`

In [17]:
x = torch.tensor([1, 2, 3, 4])
print(x.dim(), x)

1 tensor([1, 2, 3, 4])


In [8]:
torch.unsqueeze(x, 0)


tensor([[1, 2, 3, 4]])

In [19]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

# 测试激活函数

In [22]:
m = torch.nn.Hardtanh(-2, 2)
input = Variable(torch.randn(2) * 3)
print(input)
print(m(input))


tensor([1.4913, 1.8762])
tensor([1.4913, 1.8762])


In [23]:
m = torch.nn.ReLU()
input = Variable(torch.randn(2) * 3)
print(input)
print(m(input))

tensor([-0.4232,  1.1706])
tensor([0.0000, 1.1706])


# 测试sortmax

In [24]:
# 给定的维度：如行
m = torch.nn.Softmax(dim=0)
input = Variable(torch.randn(2) * 3)
print(input)
print(m(input))

tensor([ 0.6905, -0.6401])
tensor([0.7910, 0.2090])
